### ISSUE TITLE
Browser.tf site gone?

### ISSUE THREAD

**Issue by Sonic5435325** [gamemann/Browser.TF#1]
I used to look for TF2 servers with this site. Will it ever return?

**Comment by gamemann** [comment]
I wasn't able to afford the domain in time last year and when I had the money afterwards, a company had already purchased it :disappointed:. The company appeared to be reselling the domain, but when I contacted them, they never responded to me.

However, since I have other domains, I may be able to set it up on a sub-domain for https://bestservers.io (e.g. tf2.bestservers.io). I just would need to experiment with old PHP versions since the site's PHP code was pretty outdated. I'm also going to make a new server browser in the future with the domain https://bestservers.io/ (source code will be [here](https://github.com/bestserversio/bestservers)) that'll support many games including TF2 and come with many more features. I'm currently working on https://bestmods.io/ (source code [here](https://github.com/bestmods)) and hope to make Best Servers similar with additional features for game servers specifically!

Honestly really neat to hear others used Browser.TF though! I didn't expect anybody to really use it when I initially made it back in 2015/2016.

**Comment by Sonic5435325** [comment]
I actually discovered one of my main servers with your browser, will the layout be the same?

**Comment by gamemann** [comment]
I don't know what Best Servers will look like yet since it isn't far enough in development. I'm thinking of using features like infinite scrolling similar to https://bestmods.io/

The Browser.TF website will look exactly the same as before. The domain likely will be `btf.bestservers.io` when I set everything back up. I'll likely set things back up this weekend or early next week.

**Comment by gamemann** [comment]
I decided to set it up today. It should be available at https://btf.bestservers.io/ and appears to be running fine from what I see.

**Comment by Sonic5435325** [comment]
Excellent! I'll add it to my favorites. Thank you so much. :)

**Comment by gamemann** [comment]
You're welcome! I'm going to close this issue for now, but if you have any other questions, feel free to reopen!

**Comment by Sonic5435325** [comment]
@gamemann Just one more question. How long will this specific server search stay around, and will the layout stay the same?
I like the simplicity of the site as well as how easy it is to find thousands of servers quickly and reliably compared to TF2's old, broken in game server search.

**Comment by gamemann** [comment]
@Sonic5435325 I'll keep the Browser.TF website untouched so you'll always have that in the case you don't like the newer website :smile:

The new website will be at `bestservers.io` (not `btf.bestservers.io`).
